config/routes.rb
Rails.application.routes.draw do

  resources :searches, only: [:new, :create, :index]

  root 'searches#index'

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :search
end

app/models/search.rb
class Search < ActiveRecord::Base
	has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
require 'open-uri'

class SearchesController < ApplicationController

  def index
    if session[:show]
      search = Search.last
      @found_reviews = search.reviews if search    
    end
    session[:show] = false
  end

  def new
    @search = Search.new
  end

  def create
    url = "https://www.walmart.com/reviews/product/#{search_params[:product_id]}"
    key_words = search_params[:text].split(' ')
    doc = open(url) { |f| Hpricot(f) }
    
    last_page_node = doc.search(".paginator-list .js-pagination.link").last
    page_count = last_page_node ? last_page_node.inner_html.to_i : 1

    counter = 0
    items = []

    @search = Search.create(search_params)

    (1..page_count).each do |page|
       doc = open(url + "?page=#{page}") { |f| Hpricot(f) }

       doc.search(".js-review-list .customer-review").each do |review|
         
        text = review.search(".customer-review-body .customer-review-text").first.inner_html

         match = true
         key_words.each do |word|
           if !text.match(/\b(#{word})\b/i)
              match = false
              break
           end
         end

         if match 
            counter += 1
            date = review.search(".customer-review-body .customer-review-date").first.inner_html 
            nick = review.search(".customer-review-body .js-nick-name").first.inner_html 
            title = review.search(".customer-review-body .customer-review-title").first.inner_html             

            @search.reviews << Review.create(title: title, nick: nick, date: date, text: text)            
         end
       end 
    end
    session[:show] = true
    redirect_to :root, notice: "Found #{counter} reviews"
  end

    private
    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:product_id, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallmart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit "Search for reviews" %>
  </div>
<% end %>

app/views/searches/index.html.erb
<h1>Search for Product Reviews</h1>

<p id="notice"><%= notice %></p>

<% if @found_reviews %>
  <table>
   <tr>
   <th>Nick</th><th>Date</th><th>Title</th><th>Text</th>
   </tr>
  <% @found_reviews.each do |review| %>
      <tr>
      <td>
        <%= review.nick.html_safe %>
      </td>
      <td>
        <%= review.date.html_safe %>
      </td>
      <td>
        <%= review.title.html_safe %>
      </td>
      <td>
        <%= review.text.html_safe %>
      </td>
      </tr>
  <% end %>
  </table>
<% end %>

<%= link_to 'New Search', new_search_path %>

app/views/searches/new.html.erb
<h1>New Search</h1>

<p id="notice"><%= notice %></p>


<%= render 'form' %>

<%= link_to 'Back', searches_path %>